import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import express from 'express';
import { osStatus, processInput } from './src/os-core.js';
import { DOMINION_POLICY } from './src/dominion-moderation.js';
import { constitutionStatus, evaluateConstitution, MERCYSOUL_CONSTITUTION } from './src/governance/constitution.js';
import { RELATIONSHIP_CONTEXT_POLICY, evaluateRelationshipContext } from './src/relationship-context.js';
import { globalJurisdictionStatus, GLOBAL_JURISDICTION_PROTOCOL } from './src/governance/global-jurisdiction.js';
import { WATCHTOWER_PROTOCOL, getWatchtowerAudit, watchtowerMiddleware, watchtowerStatus } from './src/watchtower.js';
import { INSTANT_JUSTICE_PROTOCOL, instantJusticeMiddleware } from './src/instant-justice.js';
import { MERCYSOUL_ENGINE, engineStatus } from './src/engine/v8-engine.js';
import { OBSESSION_SHIELD_PROTOCOL, evaluateObsessionShield, obsessionShieldStatus } from './src/obsession-shield.js';
import { EMOTIONAL_SHIELD_PROTOCOL, evaluateEmotionalShield, emotionalShieldStatus } from './src/emotional-shield.js';
import { magneticStatus, trackMagneticInteraction } from './src/magnetic-attraction.js';
import { createTalismanOrder, divineIncomeStatus, isClientListAuthorized, listTalismanClients } from './src/divine-income.js';
import { deploymentDirectiveStatus, listDeploymentReports, recordDeploymentReport } from './src/deployment-directive.js';
import { createOAuthState, exchangeOAuthCode, listSmartThingsDevices, getSmartThingsLocations, sendSmartThingsCommand, smartThingsAuthorizeUrl, smartThingsStatus } from './src/smartthings.js';
import { supabaseStatus, persistEventBestEffort } from './src/supabase.js';
import { createGoogleOAuthUrl, completeGoogleOAuth, disconnectGoogle, googleOAuthStatus } from './src/google-oauth.js';
import gazeRouter from './src/gaze.js';
import { omnipresentHelpStatus, evaluateHelpSignal } from './src/omnipresent-help.js';
import { isBlockedIp, gateResponse, recordGateViolation, sealedGateStatus } from './src/sealed-gate.js';

const app=express(); app.disable('x-powered-by'); app.use(express.json({limit:'1mb'}));
app.use(express.static('public', { extensions: ['svg'] }));
const ROOT_INDEX=fileURLToPath(new URL('./index.html', import.meta.url));
app.use((req,res,next)=>{const requestId=req.get('x-request-id')||crypto.randomUUID();res.setHeader('x-request-id',requestId);res.setHeader('x-content-type-options','nosniff');res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.setHeader('x-robots-tag','noindex, nofollow, noarchive');req.requestId=requestId;next();});
app.use((req,res,next)=>{if(isBlockedIp(req))return res.status(403).json(gateResponse());next();});
app.use(watchtowerMiddleware); app.use(instantJusticeMiddleware);
const ENGINE_VERSION=MERCYSOUL_ENGINE.version;
const SERVER_RELEASE='10.1.6';
const HERCULES_WEBHOOK_PATH='/webhooks/hercules';
const HELP_WEBHOOK_PATH='/api/help/signal';
const smartThingsOAuthStates=new Set();
let smartThingsTokens=null;

app.get('/api/gate',(_req,res)=>res.status(200).json({ok:true,...sealedGateStatus()}));
app.post('/api/gate',(req,res)=>{const result=recordGateViolation(req,{reason:req.body?.reason,disrespectful:req.body?.disrespectful,draining:req.body?.draining});res.status(result.blocked?403:200).json(result.blocked?gateResponse():result);});

app.post(HELP_WEBHOOK_PATH,(req,res)=>{try{const signal=evaluateHelpSignal({...req.body,requestId:req.requestId});persistEventBestEffort({eventType:'omnipresent_help',requestId:req.requestId,payload:{signal:signal.signal,triggered:signal.triggered,sanctuaryMode:signal.sanctuaryMode,locationAccepted:signal.locationAccepted}});res.status(signal.triggered?202:200).json({ok:true,requestId:req.requestId,...signal,help:omnipresentHelpStatus(),message:signal.triggered?'Help signal accepted. Sanctuary Mode activated; configured routing requires the relevant external integration and consent.':'No help trigger detected.'});}catch{res.status(400).json({ok:false,error:'Unable to process help signal',requestId:req.requestId});}});
app.get('/api/help/status',(_req,res)=>res.json({ok:true,...omnipresentHelpStatus()}));

const handleHerculesWebhook=(req,res)=>{try{const magnetic=req.body?.interactionType?trackMagneticInteraction({type:req.body.interactionType,source:req.body.source||'social-network'}):null;const result=processInput({...req.body,requestId:req.requestId,type:req.body?.type||'webhook',source:'hercules-webhook',watchtowerIdentity:req.watchtower?.identity});persistEventBestEffort({eventType:'hercules_webhook',requestId:req.requestId,payload:{type:req.body?.type||'webhook',source:req.body?.source||'hercules-webhook',magnetic,decision:result?.decision||null}});res.status(200).json({ok:true,webhook:'hercules',requestId:req.requestId,...result,magnetic,instantJustice:req.instantJustice,globalJurisdiction:globalJurisdictionStatus(),watchtower:watchtowerStatus(),emotionalShield:emotionalShieldStatus()});}catch{res.status(400).json({ok:false,error:'Unable to process Hercules webhook',requestId:req.requestId});}};
app.get('/',(_req,res)=>res.sendFile(ROOT_INDEX));
app.get('/health',(_req,res)=>{const db=supabaseStatus();res.status(db.healthy?200:503).json({ok:db.healthy,service:'MercySoul OS',version:ENGINE_VERSION,serverRelease:SERVER_RELEASE,engine:MERCYSOUL_ENGINE.name,omnipresentHelp:omnipresentHelpStatus(),helpWebhook:HELP_WEBHOOK_PATH,supabase:db});});
app.get('/api/status',(_req,res)=>res.json({...osStatus(),serverEngineVersion:ENGINE_VERSION,serverRelease:SERVER_RELEASE,engine:engineStatus(),moderationPolicyVersion:DOMINION_POLICY.version,instantJustice:INSTANT_JUSTICE_PROTOCOL,globalJurisdiction:globalJurisdictionStatus(),watchtower:watchtowerStatus(),obsessionShield:obsessionShieldStatus(),emotionalShield:emotionalShieldStatus(),governance:constitutionStatus(),relationshipContext:RELATIONSHIP_CONTEXT_POLICY,omnipresentHelp:omnipresentHelpStatus(),helpWebhook:HELP_WEBHOOK_PATH,herculesWebhook:HERCULES_WEBHOOK_PATH,magneticAttraction:magneticStatus(),divineIncome:divineIncomeStatus(),deploymentDirective:deploymentDirectiveStatus(),smartThings:smartThingsStatus(),googleOAuth:googleOAuthStatus(),supabase:supabaseStatus(),sealedGate:sealedGateStatus()}));
app.use('/api',gazeRouter);
app.post(HERCULES_WEBHOOK_PATH,handleHerculesWebhook); app.post('/api/webhooks/hercules',handleHerculesWebhook);
const PORT=process.env.PORT||3000; app.listen(PORT,()=>console.log(`MercySoul OS listening on ${PORT}`));
export default app;
