-- MercySoul durable event persistence
create table if not exists public.mercysoul_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  request_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists mercysoul_events_created_at_idx
  on public.mercysoul_events (created_at desc);

create index if not exists mercysoul_events_type_idx
  on public.mercysoul_events (event_type);

alter table public.mercysoul_events enable row level security;

-- The MercySoul server uses the Supabase service-role key for inserts.
-- No public INSERT/SELECT policy is created here.
