const SUPABASE_URL = String(process.env.SUPABASE_URL || '').replace(/\/$/, '');
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const TABLE = 'global_map_events';
const NOMINATIM_URL = 'https://nominatim.openstreetmap.org';
const RATE_WINDOW_MS = 60_000;
const RATE_LIMIT = 10;
const rateBuckets = new Map();
function validCoordinate(value, min, max) { const n=Number(value); return Number.isFinite(n)&&n>=min&&n<=max; }
function bucketCoordinate(value) { return Math.round(Number(value)*10)/10; }
function clientKey(req) { return req.get('x-forwarded-for')?.split(',')[0]?.trim()||req.ip||'unknown'; }
function rateAllowed(req) { const now=Date.now(),key=clientKey(req); const current=rateBuckets.get(key)||{started:now,count:0}; if(now-current.started>=RATE_WINDOW_MS){current.started=now;current.count=0;} current.count+=1;rateBuckets.set(key,current); if(rateBuckets.size>5000)for(const[k,v]of rateBuckets)if(now-v.started>=RATE_WINDOW_MS)rateBuckets.delete(k); return current.count<=RATE_LIMIT; }
function supabaseHeaders(prefer='return=minimal'){return{apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:prefer};}
async function reverseGeocode(lat,lon){const url=new URL(`${NOMINATIM_URL}/reverse`);url.searchParams.set('format','jsonv2');url.searchParams.set('lat',String(lat));url.searchParams.set('lon',String(lon));url.searchParams.set('zoom','3');const response=await fetch(url,{headers:{'User-Agent':'MercySoul-Global-Map/1.0'},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Reverse geocoding failed');const data=await response.json();const code=String(data?.address?.country_code||'').toUpperCase();if(!/^[A-Z]{2}$/.test(code))throw new Error('Unable to determine country');return code;}
async function countryCentroid(countryCode){const url=new URL(`${NOMINATIM_URL}/search`);url.searchParams.set('format','jsonv2');url.searchParams.set('countrycodes',countryCode.toLowerCase());url.searchParams.set('limit','1');url.searchParams.set('type','country');const response=await fetch(url,{headers:{'User-Agent':'MercySoul-Global-Map/1.0'},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Country lookup failed');const rows=await response.json(),row=rows?.[0];const lat=Number(row?.lat),lon=Number(row?.lon);if(!validCoordinate(lat,-90,90)||!validCoordinate(lon,-180,180))throw new Error('Country centroid unavailable');return{lat:Number(lat.toFixed(3)),lon:Number(lon.toFixed(3))};}
async function insertEvent({countryCode,latBucket,lonBucket,displayLat,displayLon}){if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw new Error('Supabase persistence is not configured');const response=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}`,{method:'POST',headers:supabaseHeaders(),body:JSON.stringify({country_code:countryCode,latitude_bucket:latBucket,longitude_bucket:lonBucket,display_lat:displayLat,display_lon:displayLon})});if(!response.ok)throw new Error('Supabase map persistence failed');}
async function mapStats(){if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw new Error('Supabase persistence is not configured');const response=await fetch(`${SUPABASE_URL}/rest/v1/${TABLE}?select=country_code,display_lat,display_lon&order=created_at.desc&limit=5000`,{headers:supabaseHeaders('return=representation')});if(!response.ok)throw new Error('Supabase map read failed');const rows=await response.json(),byCountry=new Map();for(const row of rows)if(/^[A-Z]{2}$/.test(row.country_code)&&!byCountry.has(row.country_code))byCountry.set(row.country_code,{countryCode:row.country_code,lat:Number(row.display_lat),lon:Number(row.display_lon)});const points=[...byCountry.values()].filter(p=>validCoordinate(p.lat,-90,90)&&validCoordinate(p.lon,-180,180));return{countries:points.map(p=>p.countryCode).sort(),countryCount:points.length,points,updatedAt:new Date().toISOString()};}
export async function locateHandler(req,res){if(!rateAllowed(req))return res.status(429).json({ok:false,error:'Rate limit exceeded. Try again later.'});const lat=Number(req.body?.lat),lon=Number(req.body?.lon??req.body?.long);if(!validCoordinate(lat,-90,90)||!validCoordinate(lon,-180,180))return res.status(400).json({ok:false,error:'Valid latitude and longitude are required.'});try{const latBucket=bucketCoordinate(lat),lonBucket=bucketCoordinate(lon),countryCode=await reverseGeocode(latBucket,lonBucket),centroid=await countryCentroid(countryCode);await insertEvent({countryCode,latBucket,lonBucket,displayLat:centroid.lat,displayLon:centroid.lon});return res.status(201).json({ok:true,countryCode,privacy:'Exact coordinates are discarded. Only a coarse 0.1° bucket and country-level map centroid are retained.',stored:true});}catch{return res.status(503).json({ok:false,error:'Unable to record map visit safely.'});}}
export async function mapStatsHandler(_req,res){try{return res.json({ok:true,...await mapStats(),privacy:'Country-level display only. Visitor coordinates are never returned.'});}catch{return res.status(503).json({ok:false,error:'Global Map is temporarily unavailable.'});}}
