[control]
ms-control-01 ansible_host=10.44.10.11

[compute]
ms-compute-01 ansible_host=10.44.10.21

[data]
ms-data-01 ansible_host=10.44.10.31

[storage]
ms-storage-01 ansible_host=10.44.10.41

[backup]
ms-backup-01 ansible_host=10.44.10.51

[all:vars]
ansible_user=mercysoul
ansible_python_interpreter=/usr/bin/python3
